apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2VENDQWRHZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQ0FYRFRJMU1EVXlOVEEwTlRFeU9Wb1lEekl4TWpVd05UQXhNRFExTVRJNVdqQVZNUk13RVFZRApWUVFERXdwcmRXSmxjbTVsZEdWek1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBCnNaNDRXWG9CZjFmUXNPSjUyM0N1Zmx5SEx5M2FjNXRVbWN1V1BBZUhjeEcrWW1uR2t5TnFLMzZrc1Vuc0dtZlAKMEZGWUt0RDYvVXZCbGpOM21iSnJYaFlNUGlYMlFFcHlZU0pCWEFLSDVERWIvRUJHcUJLRERLU2tJbkRtbGY0ZgptM2Jic2dnQTlMRE5kVVZqV2x5Z0dObm82N2llNlNvZjliMUh6clJBcGJ3eVYyQzQvQ1dYQmdBMW9HT1B1ZTFnCnlQblJlbjI2QzU5WndFblEyZ3lEMUxmMHR1S1ZFaks0d2dRTHUrS3BJZWIrSi9POUpUYys4M216d3ZFaDhMVXMKL1NoMnpPSnFFeEpqWGFiTkpIN3YvVzVsUGtzNWtEYkxYMEJLK09pS3RGM1FzdU51QUFjSmV3dWNDQWhXTkhVMgp6dy81cnpGTFI2QTRkS3hRc1JJT2d3SURBUUFCbzBJd1FEQU9CZ05WSFE4QkFmOEVCQU1DQXFRd0R3WURWUjBUCkFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVVzeUc3OW9TWS9PRHI0bWFBYnlrSS83SXpGaWN3RFFZSktvWkkKaHZjTkFRRUxCUUFEZ2dFQkFCeGl1VU1Id2R0YXRQaFByMFZzK2FKVnVqZVR1QWs2OEVXL0J6UWdObjl1VzRzZApsUUlZN0FtUU9xWTRjSW9uVHFTMWxPcmFlY1V1MDJwRmFHYzNlb1MwdFB3dmhsNzR5dGgvNEMvUzVmT3dzWnA0CkNhVUpBZnR3R1BWVDJoTWVHdk93d1RuMlZKWTF3WnBZczBTTG9LTmFhdXMvQ1QvSEJQdlZSdWFKS3krSXo5OTQKV1BYZ3hEOGR2R1B2QnYxeHRiVlNrbSs0VzY4cXNWaDhROEhrMmw2ZWhScm9YQlRWTjdaVW5xVnFoc2xYTE1iNwpLMG1zOHlXaUhaYmtVKzYvME8yZEg0bnhLYWU4SHVTMll0bmQ4UGdFNmtocXBKN25IMitrcmxrcnFRbW50TVlkCjlOa3JOVzZmbmhSZXp5bmhsUW4yWjA1SGdMYWorWWRLdEQ3K1Y5MD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://e9879f5e-1ec4-4fcc-9ade-a2d6007360c9.kr.vnks.ntruss.com
  name: nks_kr_lulufriends-k8s_e9879f5e-1ec4-4fcc-9ade-a2d6007360c9
contexts:
- context:
    cluster: nks_kr_lulufriends-k8s_e9879f5e-1ec4-4fcc-9ade-a2d6007360c9
    user: nks_kr_lulufriends-k8s_e9879f5e-1ec4-4fcc-9ade-a2d6007360c9
  name: nks_kr_lulufriends-k8s_e9879f5e-1ec4-4fcc-9ade-a2d6007360c9
current-context: nks_kr_lulufriends-k8s_e9879f5e-1ec4-4fcc-9ade-a2d6007360c9
kind: Config
preferences: {}
users:
- name: nks_kr_lulufriends-k8s_e9879f5e-1ec4-4fcc-9ade-a2d6007360c9
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - token
      - --clusterUuid
      - e9879f5e-1ec4-4fcc-9ade-a2d6007360c9
      - --region
      - KR
      command: ncp-iam-authenticator
      env: null
      provideClusterInfo: false
